package mypackage;

import java.time.LocalDateTime;

/**
 * Represents the bet input generated by {@link Application} and passed to
 * {@link GameService}.
 */
public class BetInputData extends BetBasicData {
	// player name
	private String playerName;

	// the time when the bet was made
	private LocalDateTime betTime;

	/**
	 * Constructor.
	 * 
	 * @param playerName
	 *            the player name
	 * @param betChoice
	 *            the bet choice
	 * @param amount
	 *            the amount of bet
	 * @param betTime
	 *            when the bet was made
	 */
	public BetInputData(String playerName, String betChoice, double amount, LocalDateTime betTime) {
		super(betChoice, amount);
		this.playerName = playerName;
		this.betTime = betTime;
	}

	/**
	 * @return the playerName
	 */
	public String getPlayerName() {
		return playerName;
	}

	/**
	 * @param playerName
	 *            the playerName to set
	 */
	public void setPlayerName(String playerName) {
		this.playerName = playerName;
	}

	/**
	 * @return the betTime
	 */
	public LocalDateTime getBetTime() {
		return betTime;
	}

	/**
	 * @param betTime
	 *            the betTime to set
	 */
	public void setBetTime(LocalDateTime betTime) {
		this.betTime = betTime;
	}
}
